msp-app/grails-app/domain/metasoft/property/core/LeaseRenewalRequest.groovy
package metasoft.property.core

class LeaseRenewalRequest implements MakerCheckable<LeaseRenewalRequest>, Loggable<LeaseRenewalRequest> {

    Lease lease;
    String actionReason; // the reason why the status must be in this new status
    Date leaseExpireDate; // the new date which the lease expire on

    boolean processed = false;  // whether this request was processed or not
    String processStatus;
    String processResponse;
    Date dateProcessed;

    Date dateCreated;
    Date lastUpdated;

    static transients = ['loggable']
    static belongsTo = [lease: Lease]

    LeaseRenewalRequestTmp leaseRenewalRequestTmp;

    static constraints = {
        dirtMaker nullable: true
        maker nullable: true
        makeDate nullable: true
        checker nullable: true
        checkDate nullable: true

        actionReason maxSize: 1024
        dateProcessed nullable: true
        processStatus nullable: true, inList: ['success', 'error']
        processResponse nullable: true
        leaseExpireDate validator: { val, obj, errors ->
            Date today = new Date().clearTime();
            if(val < today) {
                errors.rejectValue('leaseExpireDate', 'default.date.invalid.past', 'Date value should not be in the past')
            }
            if(val < obj.lease.leaseExpiryDate) {
                errors.rejectValue('leaseExpireDate', 'lease.renewal.expireDate.invalid', 'The new expire date should be after the current expire date')
            }
        }
    }

    static mapping = {
        leaseExpireDate type: 'date'
    }

}

msp-app/grails-app/controllers/metasoft/property/LeaseRenewalRequestController.groovy
package metasoft.property

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import groovy.util.logging.Slf4j
import metasoft.property.core.Lease
import metasoft.property.core.LeaseRenewalRequest
import metasoft.property.core.LeaseRenewalRequestService
import metasoft.property.core.LeaseRenewalRequestTmp

import static org.springframework.http.HttpStatus.*

@Slf4j
@Secured(['IS_AUTHENTICATED_FULLY'])
class LeaseRenewalRequestController {

    LeaseRenewalRequestService leaseRenewalRequestService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured(value=['ROLE_PERM_LEASE_READ'], httpMethod ="GET")
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond leaseRenewalRequestService.list(params), model:[leaseRenewalRequestCount: leaseRenewalRequestService.count()]
    }

    @Secured(value=['ROLE_PERM_LEASE_READ'], httpMethod ="GET")
    def show(Long id) {
        LeaseRenewalRequest leaseRenewalRequest = leaseRenewalRequestService.get(id);

        if(leaseRenewalRequest == null) {
            notFound();
            return;
        }

        Lease lease = leaseRenewalRequest.lease
        respond leaseRenewalRequest, model: [leaseRenewalRequest: leaseRenewalRequest, lease: lease]
    }

    @Secured(value=['ROLE_PERM_LEASE_WRITE'], httpMethod ="POST")
    /**
     * Tries to create a routineRequestTmp object and a Check entity pending approval from checkers.
     *
     * @return
     */
    def createRequest(LeaseRenewalRequestCommand leaseRenewalRequestCommand) {

        try {
            LeaseRenewalRequestTmp leaseRenewalRequestTmp = leaseRenewalRequestService.createRequest(leaseRenewalRequestCommand);
            respond leaseRenewalRequestTmp, status: ACCEPTED
        } catch (ValidationException e) {
            log.debug("error while creating leaseRenewalRequest entity: {}", e.message);
            respond(e.errors, status: UNPROCESSABLE_ENTITY);
        }

    }

    @Secured(value=['ROLE_PERM_LEASE_WRITE'], httpMethod ="GET")
    def edit(Long id) {
        respond leaseRenewalRequestService.get(id)
    }

    @Secured(value=['ROLE_PERM_LEASE_WRITE'], httpMethod ="PUT")
    def update(LeaseRenewalRequest leaseRenewalRequest) {
        if (leaseRenewalRequest == null) {
            notFound()
            return
        }

        try {
            leaseRenewalRequestService.save(leaseRenewalRequest)
        } catch (ValidationException e) {
            respond leaseRenewalRequest.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'leaseRenewalRequest.label', default: 'LeaseRenewalRequest'), leaseRenewalRequest.id])
                redirect leaseRenewalRequest
            }
            '*'{ respond leaseRenewalRequest, [status: OK] }
        }
    }

    @Secured(value=['ROLE_PERM_LEASE_WRITE'], httpMethod ="DELETE")
    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        leaseRenewalRequestService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'leaseRenewalRequest.label', default: 'LeaseRenewalRequest'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'leaseRenewalRequest.label', default: 'LeaseRenewalRequest'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

class LeaseRenewalRequestCommand {
    Lease lease;
    String actionReason; // the reason why the status must be in this new status
    Date leaseExpireDate; // the new date which the lease expire on

    static constraints = {
        lease validator: {Lease val, obj, errors ->
            if(val != null && val.terminated) {
                errors.rejectValue('lease', 'lease.renewal.terminated', "Renewal of a terminated lease is not allowed")
            }
        }
        actionReason maxSize: 1024
        leaseExpireDate validator: { val, obj, errors ->
            Date today = new Date().clearTime();
            if(val < today) {
                errors.rejectValue('leaseExpireDate', 'default.date.invalid.past', 'Date value should not be in the past')
            }
            if(val < obj.lease.leaseExpiryDate) {
                errors.rejectValue('leaseExpireDate', 'lease.renewal.expireDate.invalid', 'The new expire date should be after the current expire date')
            }
        }
    }

}

msp-app/grails-app/views/leaseRenewalRequest/_list.gsp
<table class="table table-striped table-bordered table-hover table-advance">
    <thead>
    <tr>
        <th>Request #</th>
        <th>Action Reason</th>
        <th>Lease No</th>
        <th>Tenant</th>
        <th>Status</th>
        <th>Action Date</th>
        <th>Requested By</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <g:if test="${leaseRenewalRequestList}">
        <g:each in="${leaseRenewalRequestList}" var="leaseRenewalRequest">
            <tr>
                <td>
                <g:link style="display: block" action="show" id="${leaseRenewalRequest.id}" >
                    ${leaseRenewalRequest.id}
                </g:link>
                </td>
                <td style="width: 20%;">${leaseRenewalRequest.actionReason}</td>
                <td>
                    <g:link style="display: block" controller="lease" action="show" id="${leaseRenewalRequest.lease.id}" >
                        ${leaseRenewalRequest.lease.leaseNumber}
                    </g:link>
                </td>
                <td>${leaseRenewalRequest.lease.tenant}</td>
                <td><mp:stateStatusLabel cssClass="mc-status" status="${leaseRenewalRequest.makerChecker.status}" text="${leaseRenewalRequest.makerChecker.status}" /></td>
                <td>${leaseRenewalRequest.actionDate.format('dd MMM, yyyy')}</td>
                <td>${leaseRenewalRequest.makerChecker?.maker?.shortName}</td>
                <td>
                    <div class="actions">
                        <button type="button" disabled="disabled" class="btn btn-xs btn-danger"  >
                            <i class="fa fa-trash"></i>
                        </button>
                    </div>
                </td>
            </tr>
        </g:each>
    </g:if>
    <g:else>
        <tr>
            <td colspan="6">
                <mp:noRecordsFound />
            </td>
        </tr>
    </g:else>
    </tbody>
</table>

msp-app/grails-app/views/leaseRenewalRequest/_page_bar.gsp
<div class="page-bar">
    <g:if test="${pageHeadTitle}">
        <div class="page-bar-header">
            <h4><i class="fa fa-refresh"></i> ${pageHeadTitle}
                <g:if test="${pageHeadSubTitle}">
                    <small>${pageHeadSubTitle}</small>
                </g:if>
            </h4>
        </div>
    </g:if>

    <div class="page-toolbar">
        <g:link controller="leaseRenewalRequest" action="index" class="btn btn-default btn-sm btn-outline ">
            <i class="fa fa-list"></i> Requests
        </g:link>
        <button type="button" disabled="disabled" class="btn blue-hoki btn-sm">
            <i class="fa fa-plus"></i> Add Request
        </button>
    </div>
</div>

msp-app/grails-app/views/leaseRenewalRequest/_page_bar_show.gsp
<div class="page-bar">
    <g:if test="${pageHeadTitle}">
        <div class="page-bar-header">
            <h4><i class="fa fa-sticky-note"></i> ${pageHeadTitle}
                <g:if test="${pageHeadSubTitle}">
                    <small>${pageHeadSubTitle}</small>
                </g:if> - <mp:makerChecker value="${leaseRenewalRequest.makerChecker}" />
            </h4>
        </div>
    </g:if>

    <div class="page-toolbar pull-left" >
         <g:if test="${!leaseRenewalRequest.isChecked()}">
             <sec:ifAnyGranted roles="ROLE_PERM_LEASE_REQUEST_CHECK">
                 <g:if test="${leaseRenewalRequest.maker?.id != applicationContext.springSecurityService.currentUser.id}">
                     <maker-checker :item-controller="'lease-renewal-request'" :item-id="leaseRenewalRequest.id" :status="'${leaseRenewalRequest.makerChecker.status}'"></maker-checker>
                 </g:if>
             </sec:ifAnyGranted>
        </g:if>
    </div>

    <div class="page-toolbar" >
        <g:link controller="leaseRenewalRequest" type="button" class="btn btn-sm blue-hoki">
            <i class="fa fa-edit"></i> Requests
        </g:link>
    </div>

</div>

msp-app/grails-app/views/leaseRenewalRequest/_search_form.gsp
<%@ page import="metasoft.property.core.LeaseStatus" %>
<!-- BEGIN Portlet PORTLET-->
<div class="portlet box yellow m-top-10">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-filter"></i> Filter
        </div>
    </div>

    <div class="portlet-body">
        <form role="form" autocomplete="off">
            <div class="form-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label">Lease Number</label>
                            <input type="text" class="form-control" name="leaseNumber" value="${params?.leaseNumber}">
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label">Status</label>
                            <g:select noSelection="['': 'Select Status....']" optionKey="code" name="leaseStatus" value="${params?.leaseStatus}" class="form-control select2" from="${LeaseStatus.list()}" />
                        </div>
                    </div>

                </div>
            </div>

            <div class="form-actions">
                <button type="submit" class="btn blue-dark"><i class="fa fa-search"></i> Search...</button>
                <button type="reset" class="btn btn-danger"><i class="fa fa-refresh"></i> Reset...</button>
            </div>

        </form>

    </div>
</div>
<!-- END Portlet PORTLET-->

msp-app/grails-app/views/leaseRenewalRequest/index.gsp
<!DOCTYPE html>
<html>
<head>
    <!-- BEGIN TEMPALTE VARS -->
    <g:set var="entityName" value="${message(code: 'leaseRenewalRequest.label', default: 'Lease Renewal Request')}" />
    <g:set var="pageHeadTitle" value="${message(code: 'leaseRenewalRequest.list.label', default: "Lease Renewal Request", args: [entityName])}" scope="request" />
    <!-- END TEMPALTE VARS -->

    <meta name="layout" content="main"/>
    <title><g:message code="leaseRenewalRequest.list.label" args="[entityName]" /></title>
</head>

<body>

<div id="main-app">
    <g:render template="page_bar" />

    <div class="row">
        <div class="col-md-12">
            <g:render template="search_form"/>
        </div>
    </div>

    <g:if test="${flash.message}">
        <g:render template="/templates/flash_message" />
    </g:if>

    <div class="row">
        <div class="col-md-12">

            <div class="portlet">
                <div class="portlet-body">
                    <div class="table-scrollable">
                        <g:render template="list" />
                    </div>
                </div>
            </div>

            <div class="pagination">
                <mp:pagination total="${leaseRenewalRequestCount ?: 0}" />
            </div>

        </div>
    </div>
</div>

</body>
</html>

msp-app/grails-app/views/leaseRenewalRequest/show.gsp
<!DOCTYPE html>
<html>
<head>
    <!-- BEGIN TEMPALTE VARS -->
    <g:set var="entityName" value="${message(code: 'leaseRenewalRequest.label', default: 'Lease')}"/>
    <g:set var="pageHeadTitle" value="Lease Renewal Request : ${leaseRenewalRequest.lease.leaseNumber}" scope="request"/>
    <!-- END TEMPALTE VARS -->

    <meta name="layout" content="main"/>
    <title><g:message value="View Renewal Request - ${leaseRenewalRequest.lease.leaseNumber}" args="[entityName]"/></title>

    <script type="text/javascript">
        var leaseRenewalRequestId = ${leaseRenewalRequest.id};
    </script>

</head>

<body>

<div id="main-app" v-cloak>

    <g:render template="page_bar_show"/>

    <div class="row">
        <div class="col-md-8">
            <!-- BEGIN Portlet PORTLET-->
            <div class="portlet box green-haze margin-top-10">
                <div class="portlet-title">
                    <div class="caption"> <i class="fa fa-list"></i> Lease Renewal Request</div>
                </div>

                <div class="portlet-body">
                    <div class="portlet-body " style="padding: 0px 10px;">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th style="width: 15%">Lease Number</th><td style="width: 35%">${leaseRenewalRequest.lease.leaseNumber}</td>
                                <th style="width: 15%">Lease Status</th><td style="width: 35%">${lease.leaseNumber}</td>
                            </tr>
                            <tr>
                                <th>Action Reason</th><td colspan="3"><p>${leaseRenewalRequest.actionReason}</p></td>
                            </tr>
                            <tr>
                                <th>Action Date</th><td>${leaseRenewalRequest.actionDate.format('dd MMM, yyyy')}</td>
                                <th>Request Status</th><td><mp:stateStatusLabel status="${leaseRenewalRequest.makerChecker.status}" cssClass="mc-status" text="${leaseRenewalRequest.makerChecker.status}" /></td>
                            </tr>
                            <tr>
                                <th>Requested By</th><td>${leaseRenewalRequest.makerChecker?.maker?.fullName}</td>
                                <th>Processed ?</th><td><mp:boolStatusLabel status="${leaseRenewalRequest.processed}" /></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END Portlet PORTLET-->

            <maker-checker :makerid="${leaseRenewalRequest.maker.id}" :controller="'lease-renewal-request'" :item-id="leaseRenewalRequest.id" :status="'${leaseRenewalRequest.makerChecker.status}'"></maker-checker>

            <!-- BEGIN Portlet PORTLET-->
            <div class="portlet box blue-hoki margin-top-10">
                <div class="portlet-title">
                    <div class="caption"> <i class="fa fa-list"></i> Request Response</div>
                </div>

                <div class="portlet-body">
                    <div class="portlet-body " style="padding: 0px 10px;">
                        <table class="table">
                            <tbody>
                            <tr>
                                <th style="width: 15%">Response Date</th><td style="width: 35%">${leaseRenewalRequest.checkDate?.format('dd MMM, yyyy') ?: '---'}</td>
                                <th style="width: 15%">Responded By</th><td style="width: 35%">${leaseRenewalRequest.checker?.fullName ?: '---'}</td>
                            </tr>
                            <tr>
                                <th>Response</th><td><p>${leaseRenewalRequest.makerChecker.comment ?: '---'}</p></td>
                                <th>Response Status</th><td><mp:stateStatusLabel status="${leaseRenewalRequest.makerChecker.status}" cssClass="mc-status" text="${leaseRenewalRequest.makerChecker.status}" /></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END Portlet PORTLET-->
        </div>
        <div class="col-md-4">
            <!-- BEGIN Portlet PORTLET-->
            <div class="portlet box grey-gallery margin-top-10">
                <div class="portlet-title">
                    <div class="caption"> <i class="fa fa-sticky-note"></i> Lease Details</div>
                </div>

                <div class="portlet-body">
                    <div class="portlet-body" style="padding: 0px 10px;">
                        <table class="table">
                            <tbody>
                            <tr><th style="width: 40%">Lease Status</th><td>${lease.leaseNumber}</td></tr>
                            <tr><th>Tenant</th><td>${lease.tenant}</td></tr>
                            <tr><th>Property</th><td>${lease.property.name}</td></tr>
                            <tr><th>Rental Unit</th><td>${lease.rentalUnit}</td></tr>
                            <tr><th>Lease Status</th><td>${mp.stateStatusClass(status: lease.leaseStatus.code, text: lease.leaseStatus.name)}</td></tr>
                            <tr><th>Start Date</th><td><g:formatDate date="${lease.leaseStartDate}" /></td></tr>
                            <tr><th>Expiry Date</th><td><g:formatDate date="${lease.leaseExpiryDate}" /></td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END Portlet PORTLET-->
        </div>
    </div>
</div>

<asset:javascript src="application-vue.js" asset-defer="true" />
<asset:javascript src="vue-apps/leaseRenewalRequest/lease-renewal-request-show.js" asset-defer="true"/>

</body>
</html>